# Generated by Django 4.2 on 2023-04-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_project_user_project_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.AlterField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(blank=True, to='core.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
