# Generated by Django 4.2 on 2023-04-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_project_users_alter_user_projects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
    ]
